# Generated by Django 4.2.11 on 2024-03-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leave_leavetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='enddate',
            field=models.DateField(help_text='coming back on ...', null=True, verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('年休', '年休'), ('AM年休', 'AM年休'), ('PM年休', 'PM年休'), ('研修', '研修'), ('その他', 'その他')], default='年休', max_length=25, null=True, verbose_name='理由'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startdate',
            field=models.DateField(help_text='leave start date is on ..', null=True, verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(default='申請中', max_length=12),
        ),
    ]
